language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:  pip install db2rest
# command to run tests, e.g. python setup.py test
script:  python scripts/db2rest-tests.py
# command to build the doc
script:  python scripts/db2rest-doc.py

